site_name: IMWG Training Repo
site_url: https://tech.pmi.or.id
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
  palette:
    primary: grey
  favicon: images/logo.png


nav:
  - Home: index.md
  - Kegiatan: kegiatan.md
  - Materi: materi.md